version: '2'

services:
    hass:
        image: homeassistant/home-assistant
        container_name: hass
        network_mode: "host"
        volumes:
            - ./config:/config
            - /etc/localtime:/etc/localtime
              #devices:
            #device/dev/ttyUSB0:/dev/ttyUSB0
            #device/dev/ttyUSB1:/dev/ttyUSB1
